apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karsajobs
  name: karsajobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
  strategy: {}
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - image: ghcr.io/medival/karsajobs:latest
          name: karsajobs
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "10.101.226.125"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_PASSWORD
      volumes:
        - name: mongodb-configmap
          configMap:
            name: mongodb-configmap
        - name: mongodb-secret
          secret:
            secretName: mongo-credentials
status: {}
